#!/bin/bash
#
# execute ssh shell
# [notice] the first line of this shell set execution engine!
#

#params
CONFIG=/home/kj/zshell/hosts.conf
USER=kj

while read host
do
  echo ----------$host-------------
  echo command: $*
  echo result: 
  ssh -n $USER@$host $*
done < $CONFIG

