#!/bin/bash


# set env params
hosts=/opt/zshells/hosts.conf
user=`whoami`

# switch of params count
param_count=$#
if (( param_count<1 )) ; then
  echo no args
  exit
fi

# loop execution
while read line
do
  echo -------------$line---------------
  ssh -n $user@$line $@
done < $hosts

