#!/bin/bash


# set env params
hosts=/opt/zshells/hosts.conf
current_host=`hostname`
user=`whoami`

# switch of param count
param_count=$#
if (( param_count!=2 )) ; then 
  echo illegal params!
  exit
fi

# loop execution
while read line
do
  if [[ $line == $current_host ]] ; then 
    continue
  fi
  echo ------------$line------------- 
  scp -r $1 $user@$line:$2
done < $hosts

